### ISSUE TITLE
Arrow icons broken in font awesome 5

### ISSUE THREAD

**Issue by kyle0440** [machouinard/aviation-weather-from-noaa#10]
Font awesome has replaced the arrow icons in FA 5 with:

sort-asc is now sort-up

sort-desc is now sort-down

After updating WordPress theme to a version which loads FA 5, this breaks the arrow icon on this plugin.

**Comment by machouinard** [comment]
This should be fixed in v0.7.1.  It's live in the WP repo now.

Thanks for the heads up!
