### ISSUE TITLE
Displaying additional info

### ISSUE THREAD

**Issue by tzurko** [machouinard/aviation-weather-from-noaa#12]
Hello,

I'm a web development student doing an internship building a new website for our local airport.   The airport guys would like to have the additional grey box weather information always to display if available, instead of turning the little black arrows.

I used the google inspector to find that if you changed both of the arrows in css from display: none to display: block they would automatically load the additional weather information.

Is this the correct way to do that?   It appears to be working.   Our website is:  https://shawanoairport.com/staging/3489/

Thank you for your assistance, great widget!  I appreciate any learning advice since I'm new to web development.

Tim 
![Screen Shot 2020-04-07 at 5 34 35 PM](https://user-images.githubusercontent.com/63322071/78725820-15211900-78f6-11ea-928c-3b2ef8792ca1.png)

**Comment by machouinard** [comment]
Still not being notified of issues.  This was handled in another forum.
I'll look into making this an option but for anyone looking to do the same, you can start with this quick and dirty method to trigger a click.  Note, you might need to adjust the selector to specify the element you want to automatically expand.

```
setTimeout( function() {
			jQuery('section#metar').trigger('click');
		}, 1000);
```
