### ISSUE TITLE
An Error Has Occured. Please reload the page and try again

### ISSUE THREAD

**Issue by rgutlon** [machouinard/aviation-weather-from-noaa#15]
Installed the widget (WordPress 5.4.2). I have access to the Aviation Weather widget ... but when I attempt to make any changes nothing is saved and this message appears. I enabled the AWFN Logs but screen indicates No Logs Found. This looks like a great solution for our site.

![image](https://user-images.githubusercontent.com/14137986/91909208-c5fbcc00-ec7a-11ea-8cb5-a378982f97db.png)

Thanks!

**Comment by rgutlon** [comment]
A quick follow-up and correction ... Metar / TAF data is returned if I use the shortcode on a page but not the actual widget.

**Comment by machouinard** [comment]
Very sorry for the delayed response.  I'll get these notifications figured out one of these days!  Hope you managed to get it figured out before now.

I just spun up a fresh site running 5.4.2 and can't recreate this.  But there are no plugins installed and it's using default TwentyTwenty.
Did you try disabling other plugins to see if that fixed it?  That's the first place I'd start.

I assume you're using v0.7.2 of this plugin.
What version of PHP are you running?  Is there anything the PHP logs?

You could also enable WP_DEBUG in wp-config.php to see if that reveals anything.

`define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', true );
@ini_set( 'display_errors', 1 );
define( 'SCRIPT_DEBUG', true );`
